change deploy pipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,16 +19,22 @@ jobs:
       - name: Setup Go Environment
         uses: actions/setup-go@v5
         with:
-          go-version: '1.22' # Update to your target Go version
+          go-version: '1.26.x' 
           cache: true
 
       - name: Install Dependencies
         run: go mod download
 
-      - name: Run Linter (GolangCI-Lint)
-        uses: golangci/golangci-lint-action@v4
-        with:
-          version: latest
+      - name: Run Code Formatter Check
+        run: |
+          # Memastikan semua kode sudah diformat standar Go
+          if [ -n "$(go fmt ./...)" ]; then
+            echo "Error: Ada kode yang belum di-format. Jalankan 'go fmt ./...' di lokal."
+            exit 1
+          fi
+
+      - name: Run Go Vet (Built-in Linter)
+        run: go vet ./...
 
       - name: Run Unit Tests
         run: go test -v -race ./...
